GENERAL:
  task: train  # train, test
  manual_seed: 123
  model_dir: model/pointgroup/pointgroup.py
  dataset_dir: data/scannetv2_inst.py
  distributed: True

DATA:
  data_root: dataset
  dataset: scannetv2
  filename_suffix: _inst_nostuff.pth

  classes: 20
  ignore_label: -100

  input_channel: 3
  scale: 50   # voxel_size = 1 / scale, scale 50(2cm)
  batch_size: 2
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4 # 4=mean

STRUCTURE:
  model_name: pointgroup
  backbone: pointnet # pointnet, pointnet++_yanx, pointnet++_shi
  m: 32 # 16 or 32
  block_residual: True
  block_reps: 2
  scatter_type: max
  unet3d_num_levels: 3
  model_mode: PointNet_point_prediction_test_PointGroup
  # 0 or Zheng_panoptic_wpointnet_PointGroup or Zheng_upper_wpointnet_PointGroup or Zheng_panoptic_wopointnet_PointGroup
  # or Zheng_upper_wopointnet_PointGroup or Jiang_original_PointGroup or Yu_refine_clustering_PointGroup
  # or Li_simple_backbone_PointGroup or Yu_refine_clustering_scorenet_PointGroup
  # or PointNet_point_prediction_test_PointGroup

  use_coords: True
  use_ori_coords: True
  pointnet_include_rgb: True

TRAIN:
  epochs: 384
  train_workers: 16 # data loader workers
  optim: Adam # Adam or SGD
  lr: 0.001
  step_epoch: 384
  multiplier: 0.5
  momentum: 0.9
  weight_decay: 0.0001
  save_freq: 16  # also eval_freq
  loss_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  # center, center_semantic, center_offset, semantic, pt_offset_norm, pt_offset_dir
  focal_loss_alpha: 0.25
  focal_loss_gamma: 2
  heatmap_sigma: 0
  min_IoU: 0.5
  offset_norm_criterion: l1 # l1 or l2 or triplet
  triplet_margin: 0.3
  triplet_p: 1
  overfitting: False
  multi_heads: 2
  refine_times: 2
  clip: False
  add_pos_enc_ref: False
  pos_enc: XYZ

  constrastive_loss: True

  fg_thresh: 0.75
  bg_thresh: 0.25

  score_scale: 50 # the minimal voxel size is 2cm
  score_fullscale: 14
  score_mode: 4 # mean

  pretrain_path:
  pretrain_module: []
  fix_module: []

  remove_class: []

GROUP:
  ### point grouping
  cluster_radius: 0.03
  cluster_meanActive: 50
  cluster_shift_meanActive: 300
  cluster_npoint_thre: 50
  cluster_sets: P # P or Q

  prepare_epochs: 128

TEST:
  split: val
  test_epoch: 384
  test_workers: 16
  test_seed: 567

  TEST_NMS_THRESH: 0.3
  TEST_SCORE_THRESH: 0.09
  TEST_NPOINT_THRESH: 100
  TEST_DIST_THRESH: 2

  eval: True
  save_grid_points: False
  save_semantic: False
  save_pt_offsets: False
  save_instance: False
  save_pt_shifted_coords: False